export const POSTS_HOST = process.env.REACT_APP_POSTS_SERVICE_HOST
export const POSTS_PORT = process.env.REACT_APP_POSTS_SERVICE_PORT
export const POSTS_URL = `http://${POSTS_HOST}:${POSTS_PORT}`

export const COMMENTS_HOST = process.env.REACT_APP_COMMENTS_SERVICE_HOST
export const COMMENTS_PORT = process.env.REACT_APP_COMMENTS_SERVICE_PORT
export const COMMENTS_URL = `http://${COMMENTS_HOST}:${COMMENTS_PORT}`

export const AGGREGATION_HOST = process.env.REACT_APP_AGGREGATION_SERVICE_HOST
export const AGGREGATION_PORT = process.env.REACT_APP_AGGREGATION_SERVICE_PORT
export const AGGREGATION_URL = `http://${AGGREGATION_HOST}:${AGGREGATION_PORT}`